name: Docker Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Nogginbox.MailForwarder.Server/Dockerfile
          push: true
          tags: |
            nogginbox/mailforwardserver:latest
            nogginbox/mailforwardserver:${{ github.ref_name | replace('/', '-') }}-${{ github.run_number }}-${{ github.run_id }}

